### ISSUE TITLE
would you add  colab demo ??

### ISSUE THREAD

**Issue by Johnson-yue** [lin-shuyu/ladder-latent-data-distribution-modelling#1]
Hi, the tensorflow have many version ， and it is difficult to use， so would you plan to add demo code to colab？？

**Comment by lin-shuyu** [comment]
Hi Johnson, 

We will look into it. 

I understand the potential version conflicts between different projects. We suggest to create a virtualenv for this project and contain all the libraries needed only in the environment. The instruction of how to do so is given in the Readme file. 

I will ping you back when we add the Colab. 

Best wishes,
Lin

**Comment by r0nn13** [comment]
Hi Johnson.

Before we add the demo, it should be easy to run the code in Colab directly. For example, to start training with MNIST simply run the following in a Colab notebook:
```
%tensorflow_version 1.x
!git clone https://github.com/lin-shuyu/ladder-latent-data-distribution-modelling.git
!python3 ladder-latent-data-distribution-modelling/train.py --config ladder-latent-data-distribution-modelling/codes/mnist_digit_config.json
```
Remember to set the runtime to GPU for fast training!

Best,
Ronnie

**Comment by Johnson-yue** [comment]
@r0nn13 @lin-shuyu  Thank you ，I will try it

**Comment by lin-shuyu** [comment]
It seems the problem has been resolved.

**Comment by Johnson-yue** [comment]
@lin-shuyu  yes， I can run the code with colab, but not work for local,  maybe verison of tf or cuda have some trouble..,   anyway, thank you maybe I will rewrite with pytorch , tf is difficult to use
